name: 'goods-web'
port: 8082
host: "127.0.0.1"
tags: ["bff","goods-web"],

goods_srv:
  host: '127.0.0.1'
  port: 50052
  server_name: 'goods-srv'

jwt:
  key: 'dkdk@sksk$#@@'
  expire: 864000
  issuer: go-bff


redis:
  host: '127.0.0.1'
  port: 6379

consul:
  host: '127.0.0.1'
  port: 8500

