name: 'user-web'
port: 8081
host: "127.0.0.1"
tags: ["bff","user-web"],
user_srv:
  host: '127.0.0.1'
  port: 50052
  server_name: 'user-srv'

jwt:
  key: 'dkdk@sksk$#@@'
  expire: 864000
  issuer: go-bff


redis:
  host: '127.0.0.1'
  port: 6379

consul:
  host: '127.0.0.1'
  port: 8500

